HOFF-637-Update-IMA-to-HOF-v20.4.0
UKHomeOffice/ima pull request #101
Opened 2024-03-05 14:50 UTC by TemitopeAyokuHO

## What?
[HOFF-637 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-637).- changing Queen's crown to King's crown logo
 
## Why?
The Gov.uk crown logo changed
 
## How?
npm install hof@20.4.0
 
## Testing?
Tested locally
 
## Screenshots (optional)
 
![Screenshot 2024-02-29 at 12 18 43](https://github.com/UKHomeOffice/ima/assets/138882912/b683458a-ac09-43ee-8b04-8d16c3328204)

2024-03-05 23:45 UTC, Rhodine-orleans-lindsay requested changes

2024-03-05 23:45 UTC, Rhodine-orleans-lindsay commented on package-lock.json
Please delete this file - we use yarn.lock so don't need package-lock.json(it was probably created by running ```npm install``` instead of ```yarn install```)

2024-03-05 23:45 UTC, Rhodine-orleans-lindsay commented on data/uans-data-2023-11-16.json
Can you remove this file from your commit please? It doesn't need to be updated and should be ignored by git

2024-03-06 09:20 UTC, TemitopeAyokuHO commented on package-lock.json
removed

2024-03-06 09:20 UTC, TemitopeAyokuHO commented on data/uans-data-2023-11-16.json
removed

2024-03-06 14:24 UTC, closed without merging