Imb 23
UKHomeOffice/ima pull request #25
Opened 2023-10-23 12:47 UTC by muthrajan

Case worker down load  files when they receive email link and the user has already uploaded the files.

2023-11-22 16:43 UTC, Rhodine-orleans-lindsay requested changes

2023-11-23 20:46 UTC, muthrajan commented on README.md
> +If you want to run locally make sure you have different ports for Html-pdf-converter and filevault.  In order to download files from the email link received by caseworker, keycloak env variables KEYC
README file changed in additional envs section and availability in Keybase removed.

2023-11-23 20:47 UTC, muthrajan commented on apps/ima/translations/src/en/validation.json
> -  "who-are-you": {
who-are-you validation added

2023-11-23 20:47 UTC, muthrajan commented on apps/ima/views/confirmation.html
> +    {{/partials-page}}
New line  added

2023-11-23 20:48 UTC, muthrajan commented on apps/verify/index.js
> +      next: '/ima/evidence-upload' // TO BE REMOVED ONCE RELEVANT PAGES ADDED
next: '/check-inbox'  is reinstated and next: '/ima/evidence-upload' is removed

2023-11-23 20:49 UTC, muthrajan commented on apps/verify/index.js
> +  },
pages section removed

2023-11-28 11:33 UTC, Rhodine-orleans-lindsay requested changes
just a couple of changes needed (see comments). Could you also squash your commits when ready?

2023-11-28 11:50 UTC, Rhodine-orleans-lindsay commented on apps/ima/behaviours/submit.js
> +      }
What is this for?

2023-11-28 12:29 UTC, muthrajan commented on apps/ima/behaviours/submit.js
> +      }
lines 11-13 removed

2023-11-28 12:29 UTC, muthrajan commented on README.md
> +If you want to run locally make sure you have different ports for Html-pdf-converter and filevault.  In order to download files from the email link received by caseworker, keycloak env variables KEYC
changed to have to be added

2023-11-28 12:30 UTC, muthrajan commented on apps/ima/views/confirmation.html
> +
New line added

2023-11-28 12:53 UTC, muthrajan commented on apps/ima/views/confirmation.html
> +
New line corrected

2023-11-28 21:00 UTC, Rhodine-orleans-lindsay commented on apps/verify/index.js
> +      backLink: 'verify'
Can you remove this please?

2024-01-05 11:27 UTC, Rhodine-orleans-lindsay approved these changes

2024-01-05 11:35 UTC, merged