IMB-32 (Personal details) and  IMB-18 (Save and Exit)
UKHomeOffice/ima pull request #54
Opened 2023-12-06 23:30 UTC by TemitopeAyokuHO

##What
[IMB-18](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-18). (Save and Exit)

[IMB-32](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-32). (Personal details)

##why

To excuse IMA figma flow

##How
Added different pages as shown on Figma.

Add url path and declare fields name in Ima/index.js.
created field for every input component in field.js.
Add Labels and text for each pages also created template for large text.
Added Template

Create a template on Gov notify for Save and Exit email once user exit and return to the application.
Add the template Id to config.js file and make a reference in .env file SAVE_AND_EXIT_TEMPLATEID.
Functionality for save and exit

Added a function to send email to applicant which contains new url in the save-form-session.js
##Test
Tested locally

2023-12-07 12:07 UTC, Rhodine-orleans-lindsay requested changes
See comments

2023-12-07 12:07 UTC, Rhodine-orleans-lindsay commented on apps/ima/translations/src/en/fields.json
> -    "legend": "Who are you?",
keep this in

2023-12-07 12:07 UTC, Rhodine-orleans-lindsay commented on apps/ima/translations/src/en/pages.json
> +  },
remove this

2023-12-07 12:07 UTC, Rhodine-orleans-lindsay commented on apps/ima/views/content/cannot-use-form.md
> +<span>You can only use this form if you are in the UK.</span>
you don't need the span tag

2023-12-07 12:07 UTC, Rhodine-orleans-lindsay commented on apps/ima/views/save-and-exit.html
> +    <div class="other-details">
other-details class has no styling in css so this div and class is not needed and can be removed

2023-12-07 12:07 UTC, Rhodine-orleans-lindsay commented on apps/ima/views/helper-details.html
> +  <p class="other-details">
remove other-details class

2023-12-07 16:53 UTC, Rhodine-orleans-lindsay requested changes
See comments. there is also a .DS_Store that has been added to the could you remove this please? When you done could you squash your commits please also make clear what changes apply to what ticket as there are two tickets in one PR  e.g. 

> IMB-32 (Personal details pages) and IMB-18 (Save and Exit pages)
> - IMB-18 (Save and Exit)

- >  - bullet point 1
- >  - bullet point 2, etc

> - IMB-32 (Personal details)

- >  - bullet point 1
- >  - bullet point 2, etc

2023-12-07 16:53 UTC, Rhodine-orleans-lindsay commented on apps/ima/behaviours/save-form-session.js
> -
keep the space

2023-12-08 10:06 UTC, Rhodine-orleans-lindsay approved these changes

2023-12-08 10:08 UTC, TemitopeAyokuHO commented
Test url -  ima-imb-18-and-imb-32.internal.branch.sas-notprod.homeoffice.gov.uk

2024-01-05 23:05 UTC, merged

2024-01-05 23:06 UTC, TemitopeAyokuHO commented
Test confirmed ok